### ISSUE TITLE
Error: $ operator is invalid for atomic vectors

### ISSUE THREAD

**Issue by jhurst5** [XiaoleiLiuBio/MVP#12]
Hi Xiaolei,

I am getting the following error

    [1] "Current loop: 2 out of maximum of 10"
    [1] "Optimizing Pseudo QTNs..."
    Error: $ operator is invalid for atomic vectors
    In addition: Warning messages:
    1: In ID.GP/bin.size :
     longer object length is not a multiple of shorter object length
    2: In if (!is.na(inclosure.size)) { :
      the condition has length > 1 and only the first element will be used
    3: In parallel::mclapply(1:m, seqQTN.optimize.parallel, mc.cores = ncpus) :
      all scheduled cores encountered errors in user code
    Execution halted

I have tried changing minor things, but cannot figure out what the issue is. Any help would be appreciated.

**Comment by jhurst5** [comment]
Here is the input:
> genotype = attach.big.matrix("/path/mvp4.hmp.geno.desc")

> phenotype = read.table("/path/mvp4.hmp.phe", head=TRUE)

> map = read.table("/path/mvp4.hmp.map", head=TRUE)

> myMVP = MVP(
phe=phenotype, 
geno=genotype, 
map=map, 
nPC.FarmCPU=3, 
perc = 1, 
priority="speed", 
ncpus=5, 
vc.method="EMMA", 
maxLoop=10, 
method.bin="EMMA", 
threshold=0.05, 
method="FarmCPU"
)

**Comment by jhurst5** [comment]
In addition, when I set Max Loop to 1, it runs to completion

**Comment by XiaoleiLiuBio** [comment]
Could you please check if there are non numeric records in second and third column in map file?

**Comment by jhurst5** [comment]
No, there are no non-numeric records.

**Comment by XiaoleiLiuBio** [comment]
Please send me (xiaoleiliu@mail.hzau.edu.cn) a demo data that can repeat the error, I will test and debug it. Thank you.
