### ISSUE TITLE
use significant SNP as CV, permutation of FarmCPU

### ISSUE THREAD

**Issue by tanyongjun0815** [XiaoleiLiuBio/MVP#14]
Hi Xiaolei,
   thank you for develop such a convenient package. I have some questions:
  1,  I hve read your paper on plos genetics, I think FarmCPU can detect epstasis loci.  But new loci ware detected when previous significant SNP added to CV (somebody call this SNP-fix, p value of new loci was just excess the threshold). is that needed to add significant SNP as CV for FarmCPU model?
  2, when I use permutation to set threshold on farmcpu model, MVP display "GLM", is that right?
can you tell me? (my statistics backgroud was weak, you just need tell me what was right)
thank you.

**Comment by hyacz** [comment]
Q1:  
You don't have to manually add SNP as CV, FarmCPU will do this, automatically.

Q2:  
May be a display error.  When you set _maxLoop_ to 1, the FarmCPU is equivalent to GLM, but he should still display “FarmCPU”.

**Comment by tanyongjun0815** [comment]
OK, i got it, thanks for your reply.

**Comment by hyacz** [comment]
closed. if you have any other questions, feel free to open a new issue.
