### ISSUE TITLE
Windows在安装最后一步时总是不成功怎么办

### ISSUE THREAD

**Issue by xi532654980** [XiaoleiLiuBio/MVP#18]
错误代码：
> devtools::install_github("xiaoleiLiubio/MVP")
Installation failed: Failed to connect to raw.githubusercontent.com port 443: Timed out
> devtools::install_github("xiaoleiLiubio/MVP")
Downloading GitHub repo xiaoleiLiubio/MVP@master
from URL https://api.github.com/repos/xiaoleiLiubio/MVP/zipball/master
Installation failed: transfer closed with outstanding read data remaining

**Comment by xi532654980** [comment]
No problem with other packages, only this package is always interrupted.

**Comment by hyacz** [comment]
This is due to the instability of network transmission. now that we have reduced the size of the package, this problem should no longer occur.
