### ISSUE TITLE
When calculating kinship, "Error: cannot allocate vector of size 56.4 Gb"

### ISSUE THREAD

**Issue by naglemi** [XiaoleiLiuBio/MVP#22]
There's at least one, possibly two problems here. I'm trying to use MVP.Data to prepare my data in PLINK binary format for FarmCPU. I first noticed something was possibly wrong when MVP had written about 25% of the SNP markers (8.2M total)... at this point, the .geno.bin output stopped increasing in size. It had reached 7GB and stayed at this size from the time the console said "Number of markers written into BIG file" was ~2M to when it was ~8M. The .bed input is 28GB, yet the largest output was this 7GB .geno.bin.

Also, I appear to be unable to make a kinship matrix once writing markers into the BIG file is complete. This problem is shown below, below the command I used.

```
>MVP.Data(fileBed="my_in_prefix",
+          filePhe="my_pheno_data",
+          fileKin=TRUE,
+          filePC=TRUE,
+          out="my_out_prefix"    
+ )
```
```
[1] "Number of Markers Written into BIG File: 8252993"
[1] "Preparation for Genotype data is done!"
[1] "Preparation for PHENOTYPE data is done!"
[1] "Calculate KINSHIP using Vanraden method..."
Error: cannot allocate vector of size 56.4 Gb
```
This was followed by R crashing in the way it normally does when too much memory is used. I thought 64GB RAM would be enough for our 28GB SNP set, so that's all I asked for. Our admins can quickly add more to the virtual machine I'm working on if needed. If this is the problem, how much RAM should they add for us to be sure the whole process (from MVP.Data through FarmCPU) will work?

I have a kinship matrix prepared by EMMAX-kin, so would it be more wise for me to import and parse that one than to try making a new kinship matrix?

At this point in time, we have to use this large SNP set, which has already been filtered based on 5% maf... We can do more filtering later, but first need to make sure we can replicate results with the 8.2M set across multiple platforms.

Thanks much for your time!

**Comment by XiaoleiLiuBio** [comment]
Please check following possible reasons: 
1. It seems that "cannot allocate vector of size" issue occurs in 32 bit R verstion. Is the R version you used is 64 bit? and is it Microsoft R Open? 
2. Please set the "priority" to "memory" option and set the "maxLines" parameter for kinship calculation function to save memory

**Comment by naglemi** [comment]
Thanks, Xiaolei. I'm working in 64bit as indicated by sys.info().
I set maxlines to 10000 and priority to "memory". I'm now getting a different, but similar error. Now instead of having the maximum vector size problem with kinship calculations, I get it with PCA calculations.

[1] "Number of Markers Written into BIG File: 8250000"
[1] "Number of Markers Written into BIG File: 8252993"
[1] "Preparation for Genotype data is done!"
[1] "Preparation for PHENOTYPE data is done!"
[1] "Calculate KINSHIP using Vanraden method..."
[1] "Z assignment..."
[1] "Assignment done!"
[1] "Preparation for Kinship matrix is done!"
[1] "Principal Component Analysis Start ..."
Error: cannot allocate vector of size 56.4 Gb

**Comment by XiaoleiLiuBio** [comment]
Sorry for the late reply. It seems that the data format conversion and calculation of kinship works well. You can use following codes to get top principal components:

M <- attach.big.matrix("mvp.geno.desc")
PC <- MVP.PCA(M=M, perc=1, pcs.keep=5, memo="mvp")

If it still gives you the memory error, please adjust the "perc" parameter to use randomly selected percentage of markers to calculate PCs. Even you set the "perc" to 0.05, it would give you very similar PCs with using all available markers. Then you can write the PC table out.

**Comment by naglemi** [comment]
This issue was resolved by using the above code and changing the "perc" parameter to 0.10. The SNP set was much more dense than necessary anyway. Thanks for all the help!
