### ISSUE TITLE
output permutation threshold

### ISSUE THREAD

**Issue by mdellh2o** [XiaoleiLiuBio/MVP#23]
Hi Xiaolei,
thank you for this fantastic tool. I am using permutations to determine a significance threshold for a FarmCPU GWA. I see that the permuted threshold is correctly plotted to the resulting manhattan plots, however I cannot find the numerical value of the threshold saved anywhere in the object returned by _MVP()_ function. Am I missing something? Thank you so much

Matteo

**Comment by YinLiLin** [comment]
Hi! Matteo,

Thank you for using MVP package!
MVP doesn't return the significance threshold of permutations, but it is printed on your terminal as following: 
![print](https://user-images.githubusercontent.com/12557293/42546798-9940b54c-84f1-11e8-8126-12b43ff1e71d.png)
please check whether it is, if not, please update MVP to the latest version.

Best,
Lilin

**Comment by mdellh2o** [comment]
Hi Lilin,
thanks a lot for your help. It is all I needed
Best wishes

Matteo
