### ISSUE TITLE
Error in density.default(phe[, i]) : 'x' contains missing values

### ISSUE THREAD

**Issue by jhurst5** [XiaoleiLiuBio/MVP#24]
Hi,

I am receiving the following error:

> Error in density.default(phe[, i]) : 'x' contains missing values

There is no blank data, and all missing values are NA.

If anyone can help, it would be greatly appreciated.

**Comment by YinLiLin** [comment]
Hi,

This bug seems to happen using old version of MVP, so please update your MVP and then have a try. if it still exist, please don't hesitate to contact us.

Best!

**Comment by jhurst5** [comment]
Hi,

I updated MVP and am still getting the same error

**Comment by YinLiLin** [comment]
Sorry for that, if possible, would you please send your phenotype file to me with the email(ylilin@163.com)? I will dubug MVP with your file and update it.
Thanks!

**Comment by jhurst5** [comment]
Hi YinLiLin,

The problem was resolved after downloading a newer version of R.

Thanks for your help.
