### ISSUE TITLE
Issue with loading vcf file

### ISSUE THREAD

**Issue by strei102** [XiaoleiLiuBio/MVP#29]
Hi,

I tried to load my vcf file using the MVP.Data function to convert it to numeric but I always get the the error

"Error in VCF.Numeralization(x = tt2[-c(1:9)][index], impute = SNP.impute) : object 'maxA' not found"

I hope you can help me.

Cheers,

Stephan

**Comment by hyacz** [comment]
Hi, Stephan

Did you close the issue because you have solved this problem? 

If the problem persists, I guess it is because of some problems with the contents of your VCF file. Would you please share a Demo data with a small amount of marker with me?

Cheers,
Haohao

**Comment by strei102** [comment]
Hi Haohao,

yes I closed the issue because I've solved it. It turned out to be a problem with my vcf file. The genotypic information for each individual marker was to complex I had to simplify it. 

But now I have a new problem maybe you can help me to solve it. Is there a marker limit which MVP can convert from a vcf file? Because I get this error

Error in if (sum(integerVals == na.omit(as.integer(value))) != length(integerVals) |  : 
  missing value where TRUE/FALSE needed
In addition: Warning message:
In sum(integerVals == na.omit(as.integer(value))) :
  integer overflow - use sum(as.numeric(.))
Error during wrapup: long vectors not supported yet: ../../src/include/Rinlinedfuns.h:138

Cheers,
Stephan

**Comment by hyacz** [comment]
Hi, Stephan

sorry to reply to you so late. I missed the message.

Have you tried setting the priority parameter to "memory"?

see: https://github.com/XiaoleiLiuBio/MVP#vcf

Cheers,
Haohao
