### ISSUE TITLE
NA phenotype

### ISSUE THREAD

**Issue by grzybowskim** [XiaoleiLiuBio/MVP#4]
Hi Xiaolei,

first - thank you very much for information about your new package. It looks very nice and promising, i am under impressed. 

I would like to know is there any way to work with MVP with missing value in phenotype? I generate MVP data (phenotype file have some missing data) and i try to start analysis (only FarmCPU) but i got following error: 
when i used FaST-LMM option:

Error in if (llresults[[i]]$LL > LL.save) { : 
  missing value where TRUE/FALSE needed
In addition: Warning messages:
1: In FUN(newX[, i], ...) : no non-missing arguments to min; returning Inf
2: In FUN(newX[, i], ...) : no non-missing arguments to min; returning Inf
3: In min(P[P != 0], na.rm = TRUE) :
  no non-missing arguments to min; returning Inf
4: In if (!is.na(inclosure.size)) { :
  the condition has length > 1 and only the first element will be used

and when i use static:

Error in seq.int(from, to, length.out = n) : 'from' must be finite
In addition: Warning messages:
1: In FUN(newX[, i], ...) : no non-missing arguments to min; returning Inf
2: In FUN(newX[, i], ...) : no non-missing arguments to min; returning Inf
3: In min(P[P != 0], na.rm = TRUE) :
  no non-missing arguments to min; returning Inf
4: In if (!is.na(inclosure.size)) { :
  the condition has length > 1 and only the first element will be used
5: In min(myPrior, na.rm = TRUE) :
  no non-missing arguments to min; returning Inf
6: In min(P[P != 0], na.rm = TRUE) :
  no non-missing arguments to min; returning Inf

You can repeat this error by setting up any value in demo data with NA. In basic FarmCPU package my data works well.

Best,
Marcin

**Comment by XiaoleiLiuBio** [comment]
Hi Marcin,

Thank you for pointing out the issue. MVP accept NA value, we are now making some tests on speed and memory, some codes are commented out. I will let you know when we figure it out. It should be a couple of hours later.

Best,
Xiaolei

**Comment by grzybowskim** [comment]
Hi Xiaolei,
thank you for your response and explanation. I am looking forward for info from you. 
Best,
Marcin

**Comment by XiaoleiLiuBio** [comment]
Hi Marcin,

We just finished the test. Please reinstall MVP and try again.

Best,
Xiaolei

**Comment by grzybowskim** [comment]
Hi Xiaolei,
thank you for info - now it works perfect. 

I have one more issue: does p.threshold parameter works same as in basic FarmCPU package? For example if i don't set this parameter on demo data analysis goes fine (other parameters as default) but if i set it to even 0.01/nrow(map) i got completely different results which is strange to me. I expect to get the same results. You can repeat this strange results with demo data. 
I wont to use  p.threshold from permutation test in my normal analysis so i will be grateful for any advice. Currently i am unable to repeat my results from basic FarmCPU with manually setting this parameter.  

Best,
Marcin

**Comment by XiaoleiLiuBio** [comment]
Hi Marcin,

The parameter 'p.threshold' works the same in both MVP and FarmCPU.
Could you please paste the codes from both MVP and FarmCPU?
Which demo data? Then I will check.

Best,
Xiaolei

**Comment by grzybowskim** [comment]
Hi Xiaolei,

i use demo data from mvp folder in demo data (https://github.com/XiaoleiLiuBio/MVP/tree/master/demo.data/mvp). And PC from pc folder. 

Then i ran to code:
`imMVP <- MVP(
  phe=phenotype,
  geno=genotype,
  map=map,
  CV.FarmCPU=Covariates,
  priority="memory",
  ncpus=4,
  vc.method="EMMA",
  maxLoop=10,
  method.bin="static",
  method=c("FarmCPU")
 )` 

and second: 

`imMVP <- MVP(
  phe=phenotype,
  geno=genotype,
  map=map,
  CV.FarmCPU=Covariates,
  priority="memory",
  ncpus=3,
  vc.method="EMMA",
  maxLoop=10,
  method.bin="static",
  method=c("FarmCPU"),
  p.threshold = 0.01/nrow(map)
 )`

I expect same results - correct me if i am wrong. 
In FarmCPU it is:
`> FarmCPU(Y=myY[,1:2], GD = myGD, GM = myGM, CV=CV )`

`> FarmCPU(Y=myY[,1:2], GD = myGD, GM = myGM, CV=CV ,p.threshold = 0.01/nrow(myGM))`

And in this case i get the same results.

Best,
Marcin

**Comment by XiaoleiLiuBio** [comment]
Hi Marcin,

The problem solved, please check again and thank you for pointing out the issue.

Cheers,
Xiaolei

**Comment by grzybowskim** [comment]
Hi Xiaolei, 

thank you! Now it's works fine.

Best,
Marcin
