### ISSUE TITLE
Error in seq.default(0, maxbin.num, len) : invalid '(to - from)/by'

### ISSUE THREAD

**Issue by avinashkarn** [XiaoleiLiuBio/MVP#5]
Getting this error after "Visualization Start.... " 

Error in seq.default(0, maxbin.num, len) : invalid '(to - from)/by'

**Comment by XiaoleiLiuBio** [comment]
Could you please send me the SNP map information?

**Comment by avinashkarn** [comment]
Hi Xiaolei, I was able to fix the problem after re-installing MVP on Microsoft r open. Thank you for your help! I absolutely love the MVP package. It has been very helpful to my research work. In the near future, would it be possible to test epistatic interactions (gene x gene interactions) esp between significant SNPs from GWAS? Thanks!

**Comment by XiaoleiLiuBio** [comment]
Thank you for your suggestion. We are also doing research on gene by gene model, hope it will be available in MVP early next year.
