### ISSUE TITLE
 Eigen::internal::tridiagonal_qr_step rfunctions install error!

### ISSUE THREAD

**Issue by huangl12138** [XiaoleiLiuBio/MVP#6]
rfunctions install error!

I install rfunctions 
Spectra/LinAlg/TridiagEigen.h:93:49: error: no matching function for call to 'tridiagonal_qr_step(double*&, double*&, int&, int&, Eigen::PlainObjectBase<Eigen::Matrix<double, -1, -1> >::Scalar*, int&)'
             Eigen::internal::tridiagonal_qr_step(maind, subd, start, end, evecs.data(), n);
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /mnt/ilustre/users/dna/.env/lib64/R/library/RcppEigen/include/Eigen/Eigenvalues:39:0,

**Comment by XiaoleiLiuBio** [comment]
What is your operating system? Sometimes the web connection can also effect the installation. Please send me more information

**Comment by huangl12138** [comment]
I have fix it for reinstall RcppEigen but another issue when run MVP
#--------------------------------------Welcome to MVP--------------------------------------# 
#    A Memory-efficient, Visualization-enhanced, and Parallel-accelerated Tool For GWAS    # 
# Version: 0.1                                                                             # 
# Authors: Lilin Yin, Haohao Zhang, Zhiwu Zhang, Xinyun Li, Shuhong Zhao, and Xiaolei Liu  # 
# Contact: xiaoleiliu@mail.hzau.edu.cn                                                     # 
#------------------------------------------------------------------------------------------# 
[1] "Input data has 308 individuals, 7349687 markers"
[1] "Principal Component Analysis Start ..."
 means for first 10 snps:
 [1] 0 0 0 0 0 0 0 0 0 0
[1] "GWAS Start..."
[1] "General Linear Model (GLM) Start ..."
|---------------------------------------------------------------------->100.00%
[1] "****************GLM ACCOMPLISHED****************"
[1] "Mixed Linear Model (MLM) Start ..."
Error in .local(x) : 
  long vectors not supported yet: ../../src/include/Rinlinedfuns.h:138


my Code is 
for(i in 2:ncol(phenotype)){
+   imMVP <- MVP(
+     phe=phenotype[, c(1, i)],
+     geno=genotype,
+     map=map,
+     nPC.GLM=5,
+     nPC.MLM=3,
+     nPC.FarmCPU=3,
+     perc=1,
+     priority="speed",
+     ncpus=16,
+     vc.method="EMMA",
+     maxLoop=10,
+     method.bin="FaST-LMM",
+     threshold=0.05,
+     method=c("GLM", "MLM", "FarmCPU"),
+ file="pdf",
+   )
+ }

**Comment by XiaoleiLiuBio** [comment]
What is your operating system? Windows? Mac OS? LINUX?
32 bit? 64 bit?
Are you using Microsoft R Open?

**Comment by huangl12138** [comment]
64 bit linux centos 6.4

when I use priority="memory",,nothing wrong Thank you!

**Comment by XiaoleiLiuBio** [comment]
Thank you for pointing out the issue and good to know that 'memory' version works. I will debug it when I have a data with 7 million markers.
